definitions:
  dto.CreateUserDto:
    properties:
      email:
        type: string
      plainPassword:
        type: string
      username:
        type: string
    type: object
  dto.LoginDto:
    properties:
      email:
        type: string
      plainPassword:
        type: string
    type: object
  dto.TokensDto:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      operationId: login
      parameters:
      - description: login user
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses: {}
      summary: Log in
  /refresh:
    post:
      operationId: token-refresh
      parameters:
      - description: refresh tokens
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.TokensDto'
      produces:
      - application/json
      responses: {}
      summary: Refresh
  /register:
    post:
      operationId: create-user
      parameters:
      - description: register user
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserDto'
      produces:
      - application/json
      responses: {}
      summary: create a user
  /users/{id}:
    get:
      operationId: get-user-by-id
      parameters:
      - description: User ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get a user by ID
swagger: "2.0"
